pizzas/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = "pizzas"

urlpatterns = [
    path("", views.index, name="index"),
    path("pizzas/", views.pizzas, name="pizzas"),
    path("pizzas/<int:pizza_id>/", views.pizza, name="pizza"),
    path("new_comment/<int:pizza_id>/", views.new_comment, name="new_comment"),
    path("edit_comment/<int:comment_id>/", views.edit_comment, name="edit_comment"),
]

urlpatterns += staticfiles_urlpatterns()

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pizzas.urls")),
    path("users/", include("users.urls")),
]

users/urls.py
from django.urls import path, include
from . import views


app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Pizza(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Toppings"

    def __str__(self):
        return f"{self.text[:50]}..."


class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = "Comments"

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms
from .models import Pizza, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        label = {"Text:": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

pizzas/views.py
from django.shortcuts import render, redirect

from .models import Pizza, Topping, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    return render(request, "pizzas/index.html")


@login_required
def pizzas(request):
    pizzas = Pizza.objects.filter(owner=request.user).order_by("date_added")
    context = {"pizzas": pizzas}
    return render(request, "pizzas/pizzas.html", context)


@login_required
def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by("-date_added")

    if pizza.owner != request.user:
        raise Http404

    context = {"pizza": pizza, "toppings": toppings}
    return render(request, "pizzas/pizza.html", context)


@login_required
def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != "POST":
        form = CommentForm()

    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()

            return redirect("pizzas:pizza", pizza_id=pizza_id)

    context = {"pizza": pizza, "form": form}
    return render(request, "pizzas/new_comment.html", context)


@login_required
def edit_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    pizza = comment.pizza

    if pizza.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect("pizzas:pizza", pizza_id=pizza.id)

    context = {"comment": comment, "pizza": pizza, "form": form}
    return render(request, "pizzas/edit_comment.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("pizzas:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria Home Page</a>
    <a href="{% url 'pizzas:pizzas' %}">Available Pizzas</a>
    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/edit_comment.html
<body style="background-color: wheat;"></body>
{% extends "pizzas/base.html" %}

{% block content %}


<p> <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Edit comment:</p>

<form action="{% url 'pizzas:edit_comment' comment.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
<body style="background-color: wheat;"></body>


{% extends "pizzas/base.html" %}

{% block content %}


<p>Home Page</p>

<p>PIZZA PIZZA</p>

<p>
    {% load static %} <img src="{% static 'pizzas/media/home_page.jpg' %}" alt="index" />
</p>

{% endblock content %}

pizzas/templates/pizzas/new_comment.html
<body style="background-color: wheat;"></body>

{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Add a new comment:</p>


<form action="{% url 'pizzas:new_comment' pizza.id %}" method="post">

    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Add comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
<body style="background-color: wheat;"></body>
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzeria</p>

Pizza: {{ pizza }}


<ul>
    {% for topping in toppings %}
    <li>

        <p>{{topping.date_added|date:"M d, Y H:i" }} </p>
        <p>{{topping.text | linebreaks }} </p>

    <li>

        {% empty %}
    <li> There are no more toppings for this pizza yet.</li>
    {% endfor %}

    {% for comment in comments %}
    <li>

        <p>{{comment.date_added|date:"M d, Y H:i" }} </p>
        <p>{{comment.text | linebreaks }} </p>
    <li>
        <p>
            <a href="{% url 'pizzas:edit_comment' comment.id %}">Edit comments</a>
        </p>
        {% empty %}


    <li> There are no comments for this pizza yet.</li>
    {% endfor %}
    <ul>
        <p>
            <a href="{% url 'pizzas:new_comment' pizza.id %}"> Add new comment</a>
        </p>



        {% endblock content %}

pizzas/templates/pizzas/pizzas.html
<body style="background-color: wheat;"></body>

{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for p in pizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' p.id %}">{{ p }}</a>
    </li>
    {% empty %}
    <li> No pizzas have been added yet. </li>



    {% endfor %}

    <p>
        {% load static %} <img src="{% static 'pizzas/media/hp.jpg' %}" alt="Hawaiian" />
    </p>
    <p>
        {% load static %} <img src="{% static 'pizzas/media/ml.jpg' %}" alt="Meat Lovers" />
    </p>

</ul>




{% endblock content %}